# Generated by Django 3.0.6 on 2020-06-03 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_delete_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='music_url',
            new_name='music_link',
        ),
    ]
